### ISSUE TITLE
Initial Todo list

### ISSUE THREAD

**Issue by brunochan2001** [brunochan2001/Calculator-ReactNative#1]
# UI Design
[![Calculator-ReactNative](https://i.postimg.cc/jqM6cMGW/Screenshot-2024-04-14-at-9-12-36-PM.png)](https://i.postimg.cc/jqM6cMGW/Screenshot-2024-04-14-at-9-12-36-PM.png)

## Requirements
- [x] The calculator should show the result and the previous operation
- [ ] Documentation
- [ ] Deployment

## Todo List
- [x] 1. Create React Native & code base config
- [x] 2. add deps that I'll use for sure
- [x] 3. components (`button`) and layout.
- [x] 4. Calculator with complete functionality
- [x] 5. test
- [x] 6. QA, additional improvements & optimisations?
- [ ] Documentation
- [ ] Deployment
